services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./prolog:/app/prolog
      - historial_data:/data
    networks:
      - red_interna
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/sintomas"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - red_interna

networks:
  red_interna:
    driver: bridge

volumes:
  historial_data:
